# Generated by Django 5.2.6 on 2025-10-25 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProveedorPisoTecnologico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': 'Proveedor de Piso Tecnológico',
                'verbose_name_plural': 'Proveedores de Piso Tecnológico',
            },
        ),
        migrations.RenameModel(
            old_name='Proveedor',
            new_name='ProveedorInternet',
        ),
        migrations.AlterModelOptions(
            name='proveedorinternet',
            options={'verbose_name': 'Proveedor de Internet', 'verbose_name_plural': 'Proveedores de Internet'},
        ),
        migrations.AlterField(
            model_name='pisotecnologico',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestor.proveedorpisotecnologico'),
        ),
    ]
