# Generated by Django 5.2.6 on 2025-11-11 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0002_proveedorpisotecnologico_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escuela',
            name='coordenadas',
        ),
        migrations.AlterField(
            model_name='escuela',
            name='clave_provincial',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
