# Generated by Django 5.2.6 on 2025-11-11 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor', '0003_remove_escuela_coordenadas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='predio',
            name='numero_predio',
            field=models.IntegerField(unique=True),
        ),
    ]
